Repository equinor/fusion-web-components, pull requests merged in 2023-11, with the labels that each got.

#1077 fix(searchable-dropdown): click outside compares against element
  .changeset/twelve-rats-press.md
  packages/searchable-dropdown/src/provider/controller.ts
  packages/searchable-dropdown/src/types.ts
Labels: enhancement

#1060 chore(searchable-dropdown): removing console.log in controller
  .changeset/healthy-peaches-lay.md
  packages/searchable-dropdown/src/provider/controller.ts
Labels: Low priorirty

#1145 fix(person-avatar): account color
  .changeset/wicked-guests-bow.md
  packages/person/src/components/avatar/element.css.ts
  packages/person/src/components/avatar/element.ts
Labels: bug
