Repository equinor/fusion-web-components, pull requests merged in 2024-03, with the labels that each got.

#1454 fix(searchable-dropdown): disabled/error color
  .changeset/eleven-scissors-help.md
  packages/searchable-dropdown/src/dropdown/element.css.ts
  storybook/stories/input/searchable-dropdown-provider.ts
Labels: bug

#1456 fix(person-select): fixes task conflicts and refactoring
  .changeset/big-kids-shout.md
  packages/person/src/components/select/controller.ts
  packages/person/src/components/select/element.ts
Labels: bug, enhancement, High priority

#1460 fix wrong ending tag for personselect story
  .changeset/large-hornets-tickle.md
  storybook/stories/person/person-select.stories.ts
Labels: documentation, Low priorirty

#1461 Fix/deps/fusion web theme
  .changeset/hip-flies-crash.md
  packages/avatar/package.json
  packages/badge/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/chip/package.json
  packages/date/package.json
  packages/divider/package.json
  packages/formfield/package.json
  packages/list/package.json
  packages/markdown/package.json
  packages/person/package.json
  packages/progress-indicator/package.json
  packages/radio/package.json
  packages/searchable-dropdown/package.json
  packages/select/package.json
  packages/skeleton/package.json
  packages/switch/package.json
  packages/textinput/package.json
  packages/theme/package.json
  pnpm-lock.yaml
Labels: dependencies, Low priorirty
